language: julia
os:
  - linux
  - osx
julia:
  - 0.4
  - nightly
notifications:
  email: false
script:
  - if [[ -a .git/shallow ]]; then git fetch --unshallow; fi
  - julia --check-bounds=yes -e 'Pkg.clone(pwd()); Pkg.build("AppConf"); Pkg.test("AppConf")'

